---
apiVersion: v1
kind: Service
metadata:
  name: shop-ui
  namespace: tanzu-observability-demo-eks
spec: 
  selector:
    app: homelab-tacocat-02-tanzu-observability-demo
    service: shop-ui
  type: LoadBalancer
  ports:
  - name: application
    port: 8080
